### ISSUE TITLE
Shopping Ecommerce Website 

### ISSUE THREAD

**Issue by Soyvor** [theravi04/HacktoberFest-23#11]
Frontend Technologies:

HTML/CSS: The website's structure and design are created using HTML (Hypertext Markup Language) and CSS (Cascading Style Sheets).
JavaScript: To enhance user interactivity and implement features like product filtering, real-time price updates, and shopping cart functionality.
Responsive Design: The website is designed to be responsive, ensuring it adapts and functions well on various devices, including desktop computers, tablets, and smartphones.

label-Hacktoberfest23

**Comment by Soyvor** [comment]
Bro You Removed my tag? I cannot see my merge in the hacktoberfest page of Hacktober fest

**Comment by theravi04** [comment]
@Soyvor Assigned you this, add your name in the contributorsList .
