### ISSUE TITLE
Library Management Website

### ISSUE THREAD

**Issue by Nitish36** [theravi04/HacktoberFest-23#14]
Creating a library management website using frontend HTML, CSS, JS, and jQuery. please assign this issue under a hacktoberfest.

**Comment by theravi04** [comment]
Okay @Nitish36 I am assigning this to you.

**Comment by Nitish36** [comment]
![Output 1](https://github.com/theravi04/HacktoberFest-23/assets/91598274/098ba96f-b839-4186-b007-34f5558f2ea5)
![Output 3](https://github.com/theravi04/HacktoberFest-23/assets/91598274/6f5be7dd-93e0-450c-aff5-7bdeff878253)

**Comment by Nitish36** [comment]
1) 1st Output is the normal one with a scroll view
2) 2nd Output is one where you type the search keyword in the search section and accordingly the output is displayed on screen

**Comment by theravi04** [comment]
Okay
