### ISSUE TITLE
portfolio-website-template

### ISSUE THREAD

**Issue by ankit-0369** [theravi04/HacktoberFest-23#16]
Want to add a portfolio website design... coded completely in html and CSS only.
<img width="949" alt="Screenshot 2023-10-02 125354" src="https://github.com/theravi04/HacktoberFest-23/assets/98079557/15dbef30-d450-4b91-8224-7df2bc28466c">
Should I wait for issue to be assigned to me?

**Comment by theravi04** [comment]
@ankit-0369 Assigned you this, add your name the contributors list also.
