### ISSUE TITLE
BubbleGame

### ISSUE THREAD

**Issue by ankit-0369** [theravi04/HacktoberFest-23#17]
Its a beginner friendly game coded in Javasript ,html, and css. Will give understanding of event bubbling.

**Comment by theravi04** [comment]
@ankit-0369 Assigned you.

**Comment by theravi04** [comment]
@ankit-0369 post some pictures of the your BubbleGame here .

**Comment by ankit-0369** [comment]
This repo is excluded from hacktoberfest??
