### ISSUE TITLE
3D t-shirt design

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [theravi04/HacktoberFest-23#18]
User can create their T shirt and design .
can be build using javascript,

Please assign I am very much interested to contribute my self in hacktoberfest : )

**Comment by theravi04** [comment]
@Bharath-KumarReddy Assigned you this, add your project and your info in the contributorsList.

**Comment by Bharath-KumarReddy** [comment]
Yes sure : )

**Comment by Bharath-KumarReddy** [comment]
I had made a PR once please check it : )

**Comment by Bharath-KumarReddy** [comment]
I solved this issue and i had made a     PR 3D T shirt designer  

once please check and merge it .

Kindly inform incase of further modifications : )

**Comment by theravi04** [comment]
Okay
