### ISSUE TITLE
Few-CPP-Problems

### ISSUE THREAD

**Issue by Bhavesh122** [theravi04/HacktoberFest-23#24]

**Comment by slaughterhectic** [comment]
@Bhavesh122 I already have few cpp problems in my repository do check it and please assign it to me so  that I can contribute more

**Comment by Bhavesh122** [comment]
> @Bhavesh122 I already have few cpp problems in my repository do check it and please assign it to me so that I can contribute more
this is not my repo

**Comment by slaughterhectic** [comment]
sorry @theravi04
