### ISSUE TITLE
Implement Minimal Responsive Navigation on Homepage

### ISSUE THREAD

**Issue by trinaya-kantevari** [theravi04/HacktoberFest-23#25]
Create a simple, clean, and responsive navigation menu using HTML and CSS. This navigation menu will adapt gracefully to different screen sizes, providing an optimal user experience on both desktop and mobile devices.

**Comment by trinaya-kantevari** [comment]
@theravi04 Could you please assign me this issue? Thank you.

**Comment by theravi04** [comment]
@trinaya-kantevari Assigned you this.
