### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by Priyanshu-su30** [theravi04/HacktoberFest-23#28]
The simple To-Do List App is a simple project developed using JavaScript, CSS, and HTML. This project is an interesting project. Here, the user can add the number of to-do work details and you can see the details stored in the list form. Also, the user can delete the list items if he/she wants to remove it.  

Please assign this I am very much excited to contribute in Hactober-Fest

**Comment by theravi04** [comment]
@Priyanshu-su30 assigned you this, add your name in the contributorsList & add some pictures of your ToDo App here.

**Comment by Priyanshu-su30** [comment]
pr created pls check
