### ISSUE TITLE
Line Coding Techniques with Graphical representation

### ISSUE THREAD

**Issue by Pranav-JJ** [theravi04/HacktoberFest-23#33]
Please allow me to contribute some of the Line Coding Techniques in Java as a part of Hacktoberfest 2023 and assign me for the same.

**Comment by Pranav-JJ** [comment]
![image](https://github.com/theravi04/HacktoberFest-23/assets/109146414/1edc950b-014e-4de4-b727-09a77ec2e792)

Here's a look into one of the Line Coding graphs based on user input.

**Comment by theravi04** [comment]
@Pranav-JJ Assigned you this
