### ISSUE TITLE
TicTacToe game

### ISSUE THREAD

**Issue by spidey0101** [theravi04/HacktoberFest-23#34]
I want to add tictactoe which I recently created using python.Can you assign me this?

#Hacktoberfest
#Hacktober2023

**Comment by spidey0101** [comment]
sir please check my issue what to do after it?

**Comment by Bhavesh122** [comment]
@spidey0101 im not the owner of this repo

**Comment by spidey0101** [comment]
Yeah I know it, I was asking theravi04

**Comment by theravi04** [comment]
> I want to do this in C language please assign!

@Bhavesh122 Sure you ca do this but please raise an issue first and get it assigned.

**Comment by theravi04** [comment]
@spidey0101 I have assigned this issue to you now you can add your project and your name to contributorsList
Then create a Pull Request.

**Comment by Bhavesh122** [comment]
> > I want to do this in C language please assign!
> 
> @Bhavesh122 Sure you can do this but please raise an issue first and get it assigned.

done!
