### ISSUE TITLE
QR Code Generator

### ISSUE THREAD

**Issue by Aditi020** [theravi04/HacktoberFest-23#35]
I want to add a QR Code Generator developed using JavaScript, CSS, and HTML.
Please assign me this I am very much excited to contribute to HactoberFest.
#Hacktoberfest
#Hacktober2023

**Comment by theravi04** [comment]
@Aditi020 assigned you this.

**Comment by theravi04** [comment]
@Aditi020 can you also post some pictures of the working project here.

**Comment by Aditi020** [comment]
Sure, 

![photo_6113894390217947798_w](https://github.com/theravi04/HacktoberFest-23/assets/92170627/264e752f-d9d6-4697-a1fc-b27f6372e81f)
