### ISSUE TITLE
Implement Parallax Scrolling Effect on Homepage

### ISSUE THREAD

**Issue by trinaya-kantevari** [theravi04/HacktoberFest-23#36]
Criteria : The homepage should smoothly scroll with a Parallax effect when users scroll down. The effect should be responsive and work on various screen sizes.

**Comment by trinaya-kantevari** [comment]
@theravi04 Could you please assign me this issue? Thank you.

**Comment by theravi04** [comment]
@trinaya-kantevari assigned you this
