### ISSUE TITLE
TicTacToe game in C

### ISSUE THREAD

**Issue by Bhavesh122** [theravi04/HacktoberFest-23#38]
I want to add tictactoe which I recently created in C.Can you assign me this?

#Hacktoberfest
#Hacktober2023

**Comment by theravi04** [comment]
@Bhavesh122 assigned you this.

**Comment by Vivek789658** [comment]
Please Assign to me

**Comment by theravi04** [comment]
> Please Assign to me

@Vivek789658 Sure you can work on this but first you need to raise your own issue
