### ISSUE TITLE
Copy Sharable Link Feature - using Javascript

### ISSUE THREAD

**Issue by snehalkadwe** [theravi04/HacktoberFest-23#41]
Hello, I would like to add a small javascript project which copy the sharable link.

The "Copy Sharable Link Feature", is a JavaScript code which provides a user-friendly way for your website visitors to copy a sharable link. When they click the "Copy Link" button, the link is copied to their clipboard, and a subtle confirmation message appears. The design is clean and modern, ensuring a seamless user experience.

Could you please assign it to me under hacktoberfest 2023 label?
#Hacktoberfest
#Hacktober2023

Thanks !! :)

**Comment by theravi04** [comment]
@snehalkadwe assigned you
