### ISSUE TITLE
MazeRunner game CPP implementation

### ISSUE THREAD

**Issue by TANYA03GUPTA** [theravi04/HacktoberFest-23#43]
Hey @theravi04  I would like to add the Maze runner game's cpp  implementation in your projects code and would like to contribute. Kindly assign the issue to me and i have also submitted a PR do take a look at it. Would like  to start my hacktoberfest journey here.Could you also label the issue as hacktoberfest accepeted?

**Comment by theravi04** [comment]
@TANYA03GUPTA assigned you this

**Comment by kittoteja** [comment]
can you assigne

**Comment by TANYA03GUPTA** [comment]
@theravi04 I have submitted PR for the same . Kindly take  a look.
