### ISSUE TITLE
Python Discord Bot

### ISSUE THREAD

**Issue by MannuVilasara** [theravi04/HacktoberFest-23#7]
Its a discord bot in python with features such as modmail, economy, leveling, logs etc.
Please assign me this under HacktoberFest'23 @theravi04

**Comment by theravi04** [comment]
@MannuVilasara I am assigning you this.

**Comment by theravi04** [comment]
@MannuVilasara also add your name in the contributorsList.

**Comment by MannuVilasara** [comment]
Please Check the PR #6
